export default async function handler(req, res) {
  // This is a placeholder for the daily story generated by gemini-2.0-flash-thinking-exp-01-21.
  const story = "Today at Witellikerstrasse 20, vibrant energy fills the air as students gather in a dynamic blend of creative chaos and thoughtful conversation. The spirit of community shines at Balgrist WG in Zurich, where every day is a new chapter in our evolving story.";
  res.status(200).json({ story });
} 