name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build
      env:
        # Use dummy values for Firebase config in CI
        NEXT_PUBLIC_FIREBASE_API_KEY: 'dummy-api-key'
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'dummy-project.firebaseapp.com'
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'dummy-project'
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'dummy-project.appspot.com'
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '123456789'
        NEXT_PUBLIC_FIREBASE_APP_ID: '1:123456789:web:abc123'
        NEXT_PUBLIC_APP_VERSION: 'ci'